spring:
  # session
  application:
    name: zerocraft-user
  session:
    store-type: redis
    # 30 days expire
    timeout: 2592000
  # mysql
  datasource:
    url: jdbc:mysql://localhost:3306/zerocraft
    username: root
    password: root
  # redis
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      password:
  profiles:
    active: local
server:
  port: 8124
  servlet:
    context-path: /api
    # 30 days expire
    session:
      cookie:
        max-age: 2592000
# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: com.pp.zerocraft.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn
